package Annotations;
//here we discuss of different annotations in java
//annotation are used for better understanding of code to both human and compiler
//eg here will we implement @override annotation

class A{
   public void show()
    { 
        System.out.println("Class A show method");
    }
}
class B extends A{
    @Override                                                          //this annotation is used to inform compiler that we are overriding the method of parent class   
    public void show()
    {
        System.out.println("Class B show method");
    }

}
public class Annotations {
    public static void main( String[] args)
    {
        B obj=new B();
        obj.show();                                                        //it will call the show method of class B as it is overriding
    }
    
}
//DIFFERENT TYPES OF ANNOTATIONS
//1. @Override : used when we are overriding the method of parent class
//2. @Deprecated : used to inform that the method is deprecated and should not be used
//3. @SuppressWarnings : used to suppress the warnings generated by compiler
//4. @FunctionalInterface : used to inform that the interface is functional interface and should contain only one abstract method
//5.@GetMapping , @PostMapping , @PutMapping , @DeleteMapping : used in spring framework to map the HTTP requests to the methods of controller class
//6.@Entity , @Table , @Column : used in JPA to map the class and its fields to the database table and its columns
//7.@RestController , @RequestMapping : used in spring boot to create RESTful web services